# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e60e504d4f716c25d89946f4fd96c2635e51e5ec98c967984a7e6b8c46495c0bf99ebc61d475cd4c5fe33303d705cfcbf4771c993ce999077bc81cf741e21753

test:
  secret_key_base: 70ece2a4ec78540afd23c3d1d04d23664c07a77e252b197c5bc85323ab93295f9d1bebb80b1b70b6568b9f243f0f8d87f7e16fa907275f91920da25126bc8989

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
